name = "branching-chat-template"
main = "worker/worker.ts"
compatibility_date = "2026-02-03"
assets = { not_found_handling = "single-page-application" }
preview_urls = true

[observability]
enabled = true

[[routes]]
pattern = "branching-chat.templates.tldraw.dev"
custom_domain = true
